#!/usr/bin/env bash

print() {
  BOLD="\033[1m"
  RESET="\033[0m"
  BLUE="\033[34m"
  echo -e "${BOLD}${BLUE}$1${RESET}"
}

print "Setting up the development environment"

### ALACRITTY ###
print "Setup Alacritty"
dir=$HOME/.config/alacritty
rm -rf $dir; mkdir -p $dir
stow -t $dir alacritty

### GIT ###
print "Setup Git"
dir=$HOME/.config/git
rm -rf $dir; mkdir -p $dir
stow -t $dir git

