#!/usr/bin/env bash

RESET="\e[0m"
ERROR="\e[1;31m"
MESSAGE="\e[1;34m"

print() {
    echo -e "${MESSAGE}$1${RESET}"
}

error() {
    echo -e "${ERROR}$1${RESET}"
}

if [[ -z $CONFIG ]]; then
    CONFIG=$HOME/.config
fi

print "Setting up the development environment"

### ALACRITTY ###
print "Setup Alacritty"
rm -rf $CONFIG/alacritty; mkdir -p $CONFIG/alacritty
stow -t $CONFIG/alacritty alacritty

### GIT ###
print "Setup Git"
rm -rf $CONFIG/git; mkdir -p $CONFIG/git
stow -t $CONFIG/git git

### ZSH ###
print "Setup ZSH"
rm -rf $HOME/.zshenv $CONFIG/zsh; mkdir -p $CONFIG/zsh
stow --ignore=".zshenv" -t $CONFIG/zsh zsh
stow --ignore=".zshrc" -t $HOME zsh

### STARSHIP ###
print "Setup Starship"
rm -rf $CONFIG/starship; mkdir -p $CONFIG/starship
stow -t $CONFIG/starship starship

### OBSIDIAN ###
print "Setup Obsidian"
rm -rf $DATA/.obsidian; mkdir -p $DATA/.obsidian
stow -t $DATA/.obsidian obsidian

