#### PROMPT ####
format = """
[$username@$hostname ](bold black)\
[$directory ](bold white)\
[($git_branch )($git_commit )($git_state )($git_status )](bold purple)\
[(${custom.python} )](bold yellow)\
$character"""
right_format = """
$nix_shell"""
add_newline = false

#### GENERAL ####
[username]
format = "$user"
show_always = true

[hostname]
ssh_only = false
format = "$hostname"

[directory]
format = "$path([ $read_only]($read_only_style))"
read_only = "󰌾"

#### VCS ####
[git_branch]
format = "$branch"
only_attached = true

[git_commit]
format = "$hash"
only_detached = true

[git_state]
format = "$state"

[git_status]
format = "(\\[$untracked$deleted$renamed$modified$staged$ahead_behind\\])"
ahead = "󰜷"
behind = "󰜮"
diverged = "󰹺"
up_to_date = ""
untracked = "U"
modified = "M"
staged = "S"
renamed = "R"
deleted = "D"

#### NIX-SHELL ####
[nix_shell]
format = "$state"
impure_msg = "[](bold bright-cyan)" 
pure_msg = "[](bold white)"

#### PACKAGES ####
[custom.python] # Only appears if python is installed
description = "Python module"
when = "python --version &> /dev/null"
format = "\\[$symbol $output\\]"
symbol = ""
command = """
version=$(python --version | cut -d" " -f2 | cut -d"." -f1,2)
virtualenv=""
if [[ -n "$VIRTUAL_ENV" ]]; then
    virtualenv="($(basename $VIRTUAL_ENV))"
fi
echo "${version} ${virtualenv}"
"""
shell = ["bash"]
