backup: ENC[AES256_GCM,data:OYzsnw==,iv:NF4XG0s1VvpOX4WFKxCFl6nnmkKpfXGCGjA39E6NjYw=,tag:p5yytoDBFAcvFXq7451CHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14ssejwep34l0twqzmncx5w3k939snycu7zqcrrdrfkr8jcfxzcjs4wlv74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMXVVdWFGeXFEQWFVeVE5
            SkUvZUdXNWtTSnlLaEtvRk9CaE1TRDNuVEU4CjNFa0h0Nk82VmtwU3Q1dW1pektD
            Y2pBQXdGMHJGcldRRFVzVEFBSkYrQnMKLS0tIGxvaXp3bThXSmlsWHJFNkVaaTY4
            RFRQTU5BK29vYTN2U0hwK2ZyNTRwZ28KMXp+ZaPLJVUlQ09W5vLE9mPQtxlc1JGw
            6DQc1hTMySbu50CoRf3IdgmEmHxJSdQyqOozd29BovK+GxnvXeSqMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rv4shg0k252vnzrvvm6xdzr47yws2sts4p6u6a08dfscl3p6tsvsjnakwz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBelc0V3ZiNU0vbUFRNzFD
            SEJKcTBBYjRXQ0tDcnR0WTVEbTUxck5sQkJJCklaTG9LL2U4alI2bEgrdWtNaFdY
            YWdmUEUwZjJtSFJQMHFHc05jUFpla2cKLS0tIE9WaktoRlRNTStLRnd4SjBMakd0
            SVNwT0MzcVc1QXkvRFdWWnZ2YjJHcncK8Zkg9EqT8quz+j+Pt2ATMHYh5yGjh0mo
            9Ih0di8Y2TnZfZR0JAshJ3wZ/Kmqp6zKm2TlHtTqoEpjj6WlsOpFCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-27T11:39:30Z"
    mac: ENC[AES256_GCM,data:BTstaPC9ngW0qk1qP4VnDY5Lc0VnwUQcq83Ut3Qd3OW7veR7PDmtXI5Q5ANr1dG/P72ETUGYiMh53cUNp/28iVjFuZ0VmXmB92UXBxyGJVoJaUyoNxejcGu3d+4wYTYd2mV4ZDq5N4ygRRztYkWDVzdiy6ewuxRVxWjDHMNkcrU=,iv:sSlb8PFGmj+NHplnz7D2UgVyzZi2gfM5D5LhPM2PnOQ=,tag:JZaeqSBaKZv0jaO65k0gMA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
