restic: ENC[AES256_GCM,data:WMa0WGZX9u9SdnHWz6UFbkESThfbllY8OhzfpqK6MU0=,iv:37+bA3swZTst2ioltdhidg27SMzSvYzsu9Xsbx/9D2Q=,tag:2dsrgA2tsQOb4nEYo3o9UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ellarpjtndc0w037w7zsplfx4nfvvnc0e4cgk6n293yq0gd44sfs8v0v4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFckpFa2JwWW9hRDdQUEx5
            QzJRbTZoeHFwWkxDNU84TkdWVDd6Zzl6MFRJClhwNUd5UUVnT0ZINDBraFdpOG16
            TjdXQmtUWGlDWGhTWjZ1YllTc2ozSkEKLS0tIFp1ZGJ0RnY0M0FJQ1l5WmRNYzB1
            d1YzTGJsSDhaNVlEUE1VYStoRXFmN0UKUaW0Xfy/FvRHqj0f0Cpan9Wytx5K/b0f
            0eHF6ixmfCcc/KBMoKCCtEkcCJqGHA7mC1w/0wRf9fYhWXLMBEGU9w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63hgq52nsyu8lyr847de40nnkgf97x85s7pre5ws9kpgh26qv3sqc9grl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQWExdEtjRTBBSzd3L09N
            Z1JQSjdzZElqR3FpbU52TkxBdTlEZy8yU3lRCnRqQzlPOG5VWjF5cVJZSkJsZjBB
            QzJpb1pzaXBFYVJkbEh2Ni9xMjFRS1EKLS0tIGhNdUoxMTkzR3FwakZQU2tJTjhk
            VE15ekJkc29CdGFER21YSmI0bkRWblEKelMARjo2PN10VufcT+iJg8v1+Qair8IL
            moanX7u+/yqhSMYb0rXUHPfzeieWTwsipFUHqS3JcZ6oeej4hp/nkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T11:37:44Z"
    mac: ENC[AES256_GCM,data:zw6rtDgyNTL6i69sFAYKwHxaoMdptgKwfXyGSg8tTRvyKldWivMXd8BbNUHx/2EHSThYGwMGngpo1ao+5ZCmUOOm1K60/BHyblRvHTRh8UCMGPCAWtJg/1IeuIZ7TRKLjrD+/0R/B3A7pNrUYDjU7g0D+4E9Lipuh7OQSZd8IWQ=,iv:/X7MALOAAoEP2M7lvd7KEIFWRgCax4inKHAK0qXjMp0=,tag:TwpzydOekqjtwR+xM1oBwA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
