backup: ENC[AES256_GCM,data:YwNn3Q==,iv:zSf5zUercFM0FDjZP6gD09oqlHdzoa4kL2BXhHXIb7g=,tag:4VeqiBv58DgrLbYV88PMeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ellarpjtndc0w037w7zsplfx4nfvvnc0e4cgk6n293yq0gd44sfs8v0v4y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZjNOdlovUGVRZFpJclVn
            RHZBaGErY2xwLzliTkZYZjBxUy81dHI5UFY0ClVZaGhiTElMdEdobzRaYXd2Ympl
            VnlLb203MFVaK0NxcmhXSm9ab1VQclkKLS0tIFhGZlg4ZlFhbFJwU2VLSmovaENh
            WHh4ZkI2dStTc01vU1RtR1pSeUk3cVUKZlYgXoTu/BRiQX6lyl4rZjS1iC5baMBc
            iLVomwqXj4yc2muePEb9Blr6Ldj22rOU+SqTtECnSZneQX6c62vaeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63hgq52nsyu8lyr847de40nnkgf97x85s7pre5ws9kpgh26qv3sqc9grl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZEo3Yksya3AweHNzYnFE
            ZEl5Z2tBUGcxQlo1ejJGakh3Z0JwUkNOakFRCnUrSUR6dFhXbU5BUDd1SUpFSTFw
            NmRQM1Jia0lwKzUvclY2NE9SNlhvL0kKLS0tIERaWjQ5T1JDdlVCQW5XYVNiRU5k
            SU9hWG5LSUVZR1lxR0ZJeHZBTkRsdG8KgP3KyeL2nU5hrN/kpNX50b4j9kcw5sAY
            iONQzQF7BwQBPPp3UMQAnTJfU9fNLg8w1J6Ko0KT7X804zVRd3HT9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-14T13:13:35Z"
    mac: ENC[AES256_GCM,data:j96YTunFLa8B4ZC1h0k2MEC6Yzn0rwPP5NhNjdiNHuV6qR/eRRwSMxZGVh6GIaROaUeCSaasT5XEh+lCK4dVVl5fPeBbl2BrANAIz3IxSH2sYZOSpfCii0WMVVtr3d1VTB9j+/cPClPe69T26q4ewwzNfeRDiz7Y8w9f9npn5T0=,iv:J1mRMlS+Kp9GYxted1fqPUyzdJYLOfB5XXJbhFyjndU=,tag:AFq7BVvDxVlQ3+BEJyFnMw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
