keys:
  - &jarne age14ssejwep34l0twqzmncx5w3k939snycu7zqcrrdrfkr8jcfxzcjs4wlv74
  - &neso age1rv4shg0k252vnzrvvm6xdzr47yws2sts4p6u6a08dfscl3p6tsvsjnakwz
creation_rules:
  - path_regex: secrets/neso/[^/]+\.yaml$
    key_groups:
    - age:
      - *jarne
      - *neso

