#!/usr/bin/env bash

log() {
  script_dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
  "$script_dir/log" "$@"
}

is_installed() {
  package=$1

  # Check if the command has a version option
  "$package" --version &> /dev/null
  if [[ $? -eq 0 ]]; then
    return 0
  fi

  # Check if the command has a help option
  "$package" --help &> /dev/null
  if [[ $? -eq 0 ]]; then
    return 0
  fi
  
  "$package" -h &> /dev/null
  if [[ $? -eq 0 ]]; then
    return 0
  fi

  log error "The package '$package' is not found."
  return 1
}

ok=0
for package in "$@"; do
  is_installed "$package"
  [[ $? -ne 0 ]] && ok=1
done
[[ $ok -eq 0 ]] && exit 0 || exit 1

