#!/usr/bin/env bash

#### CHECK THE VERSION ####
getopt --test &>/dev/null
if [[ $? -ne 4 ]]; then
  echo "The enhanced version of 'getopt' is expected."
  exit 1
fi

#### PARSE THE OPTIONS ####
temp=$(mktemp)
parsed=$(getopt --options=$1 --longoptions=$2 -- "${@:3}" 2>> $temp)
if [[ $? -ne 0 ]]; then
  echo "$(cat $temp)" | sed "s/.* '-*\(.*\)'$/Unknown option '\1'/"
  exit 1
fi
rm $temp
echo $parsed
exit 0

