#!/usr/bin/env bash

#### CONSTANTS & VARIABLES ####
script_dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
script_name=$(basename $0)

themes=("ice")
themes_text_suffix=$(printf "%s, " "${themes[@]}")
theme_text="${themes_text_suffix%, }"

config="$HOME/.config"

options="hc:"
options_long="help,config:"
text_help="Usage: $script_name [OPTIONS] <theme>

Set the theme of CLI tools.
Available themes: $theme_text.

Options:
    -h, --help			Display this message
    -c <path>, --config <path>	Set the configuration path, defaults to $config"
text_info="See '$script_name --help' for more information."

ok=true

#### FUNCTIONS ####
log() {
    "$script_dir/log" "$1" "$2"
}

link() {
    name=$1
    src=$2
    target=$3

    if [[ -e "$src" ]]; then
        ln -sf "$src" "$target"
	log ok "$name"
    else
	ok=false
	log error "$name"
    fi
}

#### PROCESSING OPTIONS & ARGUMENTS ####
# Parse the options
parsed=$("$script_dir/parse_input" $options $options_long "$@")
if [[ $? -ne 0 ]]; then
    log error "$parsed"
    log error "$text_info"
    exit 1
fi
eval set -- "$parsed"

# Handle the options
while true; do
    case "$1" in
	-h|--help)
	    echo "$text_help"
	    exit 0 ;;
        -c|--config)
	    config=$2
	    shift 2 ;;
	--)
	    shift
	    break ;;
	*)
	    log error "Whoops, this should not have happened!"
	    exit 1 ;;
    esac
done

# Handle the arguments
if [[ $# -ne 1 ]]; then
    log error "We expect 1 theme to be chosen."
    log error "$text_info"
    exit 1
fi

# Check if the theme exists
theme=$1
if [[ ! $themes =~ (^|[[:space:]])$theme($|[[:space:]]) ]]; then
    log error "Unavailable theme."
    log error "$text_info"
    exit 1
fi

#### SETTING UP THE THEME ####
# Alacritty
link alacritty $config/alacritty/$theme.toml $config/alacritty/theme.toml

# Starship
link starship $config/starship/$theme.toml $config/starship/starship.toml

#### DONE ####
if [[ $ok = false ]]; then
    log error "Failed to set up the '$theme' theme."
    exit 1
fi

log ok "Successfully set up the '$theme' theme."
exit 0

